-- seed class schedules for all teachers
INSERT INTO class_schedules (teacher_id, subject_id, section_id, day_of_week, start_time, end_time, room, school_year, semester, created_at, updated_at)
VALUES
-- teacher1 - PROG1 to BSIT 2A (Monday to Sunday, 08:00-09:30, Room 201)
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PROG1'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2A'),
    'Monday',
    '08:00:00',
    '09:30:00',
    'Room 201',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PROG1'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2A'),
    'Tuesday',
    '08:00:00',
    '09:30:00',
    'Room 201',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PROG1'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2A'),
    'Wednesday',
    '08:00:00',
    '09:30:00',
    'Room 201',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PROG1'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2A'),
    'Thursday',
    '08:00:00',
    '09:30:00',
    'Room 201',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PROG1'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2A'),
    'Friday',
    '08:00:00',
    '09:30:00',
    'Room 201',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PROG1'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2A'),
    'Saturday',
    '08:00:00',
    '09:30:00',
    'Room 201',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PROG1'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2A'),
    'Sunday',
    '08:00:00',
    '09:30:00',
    'Room 201',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
-- teacher1 - PROG1 to BSIT 2B (Monday to Sunday, 10:00-11:30, Room 202)
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PROG1'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2B'),
    'Monday',
    '10:00:00',
    '11:30:00',
    'Room 202',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PROG1'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2B'),
    'Tuesday',
    '10:00:00',
    '11:30:00',
    'Room 202',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PROG1'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2B'),
    'Wednesday',
    '10:00:00',
    '11:30:00',
    'Room 202',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PROG1'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2B'),
    'Thursday',
    '10:00:00',
    '11:30:00',
    'Room 202',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PROG1'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2B'),
    'Friday',
    '10:00:00',
    '11:30:00',
    'Room 202',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PROG1'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2B'),
    'Saturday',
    '10:00:00',
    '11:30:00',
    'Room 202',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PROG1'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2B'),
    'Sunday',
    '10:00:00',
    '11:30:00',
    'Room 202',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
-- teacher1 - DSA to BSIT 2A (Monday to Sunday, 13:00-14:30)
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'DSA'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2A'),
    'Monday',
    '13:00:00',
    '14:30:00',
    'Room 201',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'DSA'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2A'),
    'Tuesday',
    '13:00:00',
    '14:30:00',
    'Room 201',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'DSA'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2A'),
    'Wednesday',
    '13:00:00',
    '14:30:00',
    'Room 201',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'DSA'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2A'),
    'Thursday',
    '13:00:00',
    '14:30:00',
    'Room 201',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'DSA'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2A'),
    'Friday',
    '13:00:00',
    '14:30:00',
    'Room 201',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'DSA'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2A'),
    'Saturday',
    '13:00:00',
    '14:30:00',
    'Room 201',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'DSA'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2A'),
    'Sunday',
    '13:00:00',
    '14:30:00',
    'Room 201',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
-- teacher1 - DSA to BSIT 2B (Monday to Sunday, 15:00-16:30)
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'DSA'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2B'),
    'Monday',
    '15:00:00',
    '16:30:00',
    'Room 202',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'DSA'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2B'),
    'Tuesday',
    '15:00:00',
    '16:30:00',
    'Room 202',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'DSA'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2B'),
    'Wednesday',
    '15:00:00',
    '16:30:00',
    'Room 202',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'DSA'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2B'),
    'Thursday',
    '15:00:00',
    '16:30:00',
    'Room 202',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'DSA'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2B'),
    'Friday',
    '15:00:00',
    '16:30:00',
    'Room 202',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'DSA'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2B'),
    'Saturday',
    '15:00:00',
    '16:30:00',
    'Room 202',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher1'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'DSA'),
    (SELECT section_id FROM sections WHERE section_name = 'BSIT 2B'),
    'Sunday',
    '15:00:00',
    '16:30:00',
    'Room 202',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
-- teacher2 - GEN-MATH to Grade 11 - STEM A (Monday to Sunday, 08:00-09:30, Room 301)
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'GEN-MATH'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 11 - STEM A'),
    'Monday',
    '08:00:00',
    '09:30:00',
    'Room 301',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'GEN-MATH'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 11 - STEM A'),
    'Tuesday',
    '08:00:00',
    '09:30:00',
    'Room 301',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'GEN-MATH'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 11 - STEM A'),
    'Wednesday',
    '08:00:00',
    '09:30:00',
    'Room 301',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'GEN-MATH'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 11 - STEM A'),
    'Thursday',
    '08:00:00',
    '09:30:00',
    'Room 301',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'GEN-MATH'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 11 - STEM A'),
    'Friday',
    '08:00:00',
    '09:30:00',
    'Room 301',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'GEN-MATH'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 11 - STEM A'),
    'Saturday',
    '08:00:00',
    '09:30:00',
    'Room 301',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'GEN-MATH'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 11 - STEM A'),
    'Sunday',
    '08:00:00',
    '09:30:00',
    'Room 301',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
-- teacher2 - PRE-CAL to Grade 11 - STEM A (Monday to Sunday, 10:00-11:30, Room 301)
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PRE-CAL'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 11 - STEM A'),
    'Monday',
    '10:00:00',
    '11:30:00',
    'Room 301',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PRE-CAL'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 11 - STEM A'),
    'Tuesday',
    '10:00:00',
    '11:30:00',
    'Room 301',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PRE-CAL'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 11 - STEM A'),
    'Wednesday',
    '10:00:00',
    '11:30:00',
    'Room 301',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PRE-CAL'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 11 - STEM A'),
    'Thursday',
    '10:00:00',
    '11:30:00',
    'Room 301',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PRE-CAL'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 11 - STEM A'),
    'Friday',
    '10:00:00',
    '11:30:00',
    'Room 301',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PRE-CAL'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 11 - STEM A'),
    'Saturday',
    '10:00:00',
    '11:30:00',
    'Room 301',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PRE-CAL'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 11 - STEM A'),
    'Sunday',
    '10:00:00',
    '11:30:00',
    'Room 301',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
-- teacher2 - ENGLISH to Grade 11 - STEM A (Monday to Sunday, 13:00-14:30, Room 301)
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'ENGLISH'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 11 - STEM A'),
    'Monday',
    '13:00:00',
    '14:30:00',
    'Room 301',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'ENGLISH'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 11 - STEM A'),
    'Tuesday',
    '13:00:00',
    '14:30:00',
    'Room 301',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'ENGLISH'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 11 - STEM A'),
    'Wednesday',
    '13:00:00',
    '14:30:00',
    'Room 301',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'ENGLISH'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 11 - STEM A'),
    'Thursday',
    '13:00:00',
    '14:30:00',
    'Room 301',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'ENGLISH'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 11 - STEM A'),
    'Friday',
    '13:00:00',
    '14:30:00',
    'Room 301',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'ENGLISH'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 11 - STEM A'),
    'Saturday',
    '13:00:00',
    '14:30:00',
    'Room 301',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'ENGLISH'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 11 - STEM A'),
    'Sunday',
    '13:00:00',
    '14:30:00',
    'Room 301',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
-- teacher2 - PHIL-HIST to Grade 12 - HUMSS A (Monday to Sunday, 08:00-09:30, Room 302)
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PHIL-HIST'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 12 - HUMSS A'),
    'Monday',
    '08:00:00',
    '09:30:00',
    'Room 302',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PHIL-HIST'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 12 - HUMSS A'),
    'Tuesday',
    '08:00:00',
    '09:30:00',
    'Room 302',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PHIL-HIST'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 12 - HUMSS A'),
    'Wednesday',
    '08:00:00',
    '09:30:00',
    'Room 302',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PHIL-HIST'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 12 - HUMSS A'),
    'Thursday',
    '08:00:00',
    '09:30:00',
    'Room 302',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PHIL-HIST'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 12 - HUMSS A'),
    'Friday',
    '08:00:00',
    '09:30:00',
    'Room 302',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PHIL-HIST'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 12 - HUMSS A'),
    'Saturday',
    '08:00:00',
    '09:30:00',
    'Room 302',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'PHIL-HIST'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 12 - HUMSS A'),
    'Sunday',
    '08:00:00',
    '09:30:00',
    'Room 302',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
-- teacher2 - SOC-SCI to Grade 12 - HUMSS A (Monday to Sunday, 10:00-11:30, Room 302)
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'SOC-SCI'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 12 - HUMSS A'),
    'Monday',
    '10:00:00',
    '11:30:00',
    'Room 302',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'SOC-SCI'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 12 - HUMSS A'),
    'Tuesday',
    '10:00:00',
    '11:30:00',
    'Room 302',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'SOC-SCI'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 12 - HUMSS A'),
    'Wednesday',
    '10:00:00',
    '11:30:00',
    'Room 302',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'SOC-SCI'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 12 - HUMSS A'),
    'Thursday',
    '10:00:00',
    '11:30:00',
    'Room 302',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'SOC-SCI'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 12 - HUMSS A'),
    'Friday',
    '10:00:00',
    '11:30:00',
    'Room 302',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'SOC-SCI'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 12 - HUMSS A'),
    'Saturday',
    '10:00:00',
    '11:30:00',
    'Room 302',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'SOC-SCI'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 12 - HUMSS A'),
    'Sunday',
    '10:00:00',
    '11:30:00',
    'Room 302',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
-- teacher2 - FILIPINO to Grade 12 - HUMSS A (Monday to Sunday, 13:00-14:30, Room 302)
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'FILIPINO'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 12 - HUMSS A'),
    'Monday',
    '13:00:00',
    '14:30:00',
    'Room 302',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'FILIPINO'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 12 - HUMSS A'),
    'Tuesday',
    '13:00:00',
    '14:30:00',
    'Room 302',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'FILIPINO'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 12 - HUMSS A'),
    'Wednesday',
    '13:00:00',
    '14:30:00',
    'Room 302',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'FILIPINO'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 12 - HUMSS A'),
    'Thursday',
    '13:00:00',
    '14:30:00',
    'Room 302',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'FILIPINO'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 12 - HUMSS A'),
    'Friday',
    '13:00:00',
    '14:30:00',
    'Room 302',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'FILIPINO'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 12 - HUMSS A'),
    'Saturday',
    '13:00:00',
    '14:30:00',
    'Room 302',
    '2025-2026',
    'First',
    NOW(),
    NOW()
),
(
    (SELECT id FROM users WHERE username = 'teacher2'),
    (SELECT subject_id FROM subjects WHERE subject_code = 'FILIPINO'),
    (SELECT section_id FROM sections WHERE section_name = 'Grade 12 - HUMSS A'),
    'Sunday',
    '13:00:00',
    '14:30:00',
    'Room 302',
    '2025-2026',
    'First',
    NOW(),
    NOW()
);
